sonar.projectKey=PhongLe7de_PlantSnap
sonar.organization=phongle7de

sonar.projectName=PlantSnap
sonar.projectVersion=1.0

sonar.sources=app/src/main
sonar.java.binaries=app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes
sonar.kotlin.source.version=1.9

sonar.tests=app/src/test,app/src/androidTest

sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

sonar.androidLint.reportPaths=app/build/reports/lint-results-debug.xml

sonar.exclusions=\
  **/R.java,\
  **/R.kt,\
  **/BuildConfig.*,\
  **/Manifest*.*,\
  **/*_MembersInjector*,\
  **/*_Factory*,\
  **/*Module_*Factory*,\
  **/*_HiltModules*,\
  **/Hilt_*,\
  **/*Hilt*Generated*,\
  **/databinding/**,\
  **/build/**,\
  **/*.xml

sonar.coverage.exclusions=\
  **/di/**,\
  **/*Module.*,\
  **/*Application.*,\
  **/model/**,\
  **/*Entity.*,\
  **/*Dto.*,\
  **/*NavRoutes*,\
  **/ui/theme/**

sonar.host.url=https://sonarcloud.io